In [0]:
import torch
import numpy as np

In [0]:
list1=([1,2],[3,4])

In [0]:
torchtens=torch.tensor(list1)

In [0]:
torchtens

tensor([[1, 2],
        [3, 4]])

In [0]:
print(type(torchtens))

<class 'torch.Tensor'>


In [0]:
np_tensor=torch.tensor(np.array([1,2,3,4,5,6]),dtype=torch.float32)

In [0]:
np_tensor

tensor([1., 2., 3., 4., 5., 6.])

In [0]:
print(type(np_tensor))

<class 'torch.Tensor'>


In [0]:
#create empty tensor
empty_tens=torch.tensor([])

In [0]:
empty_tens

tensor([])

In [0]:
torch.arange(5,10)

tensor([5, 6, 7, 8, 9])

In [0]:
torch.arange(5,30,5)

tensor([ 5, 10, 15, 20, 25])

In [0]:
torch.linspace(-10,10,5)

tensor([-10.,  -5.,   0.,   5.,  10.])

In [0]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [0]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [0]:
#identity maatrix in torch
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [0]:
torch.full((2,2),4)

tensor([[4., 4.],
        [4., 4.]])

#mathmetical operation on tensors


In [0]:
x= torch.ones((3,2))
y=torch.full((3,2),3)

In [3]:
print("x+y is :",x+y)
print("x-y is :",x-y)
print("x/y is :",x/y)
print("x*y is :",x*y)

x+y is : tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])
x-y is : tensor([[-2., -2.],
        [-2., -2.],
        [-2., -2.]])
x/y is : tensor([[0.3333, 0.3333],
        [0.3333, 0.3333],
        [0.3333, 0.3333]])
x*y is : tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])


In [0]:
# add funtion
z=x.mul(y)

In [7]:
print(z)

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])


In [8]:
#creating tensorf from numpy array
x=x.numpy()  #converting tensor into numpy array
print(type(x))

<class 'numpy.ndarray'>


In [9]:
x=torch.from_numpy(x)
print(type(x))

<class 'torch.Tensor'>


#computationaly torch is better then numpy lets verify..

In [10]:
%%time
for i in range(1000):
  var1=np.random.randn(100,100)
  var2=np.random.randn(100,100)
  var3=var1+var2

CPU times: user 858 ms, sys: 2.09 ms, total: 860 ms
Wall time: 867 ms


In [11]:
%%time
for i in range(1000):
  var1=torch.randn(100,100)
  var2=torch.randn(100,100)
  var3=var1+var2

CPU times: user 235 ms, sys: 845 µs, total: 235 ms
Wall time: 245 ms


# cuda with torch
torch.cuda.is_available()

In [12]:
torch.cuda.is_available()

True

In [13]:
torch.cuda.device_count()

1

In [14]:
torch.cuda.current_device()

0

In [15]:
#how to get gpu name
print(torch.cuda.get_device_name(0))

Tesla K80


# pytocrch tensor on gpu

In [0]:
#creating cuda object
cuda0=torch.device('cuda:0')

In [17]:
print(cuda0)

cuda:0


In [0]:
gpu_var_x=torch.ones((2,2),device=cuda0)

In [19]:
print(gpu_var_x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')


#Performance: Numpy vs Cpu torch vs Gpu torch tensors

In [20]:
#numpy
%%time
for i in range(1000):
  var1=np.random.randn(100,100)
  var2=np.random.randn(100,100)
  var3=var1+var2

CPU times: user 869 ms, sys: 1.45 ms, total: 870 ms
Wall time: 875 ms


In [21]:
#torch cpu
%%time
for i in range(1000):
  var1=torch.randn(100,100)
  var2=torch.randn(100,100)
  var3=var1+var2

CPU times: user 231 ms, sys: 0 ns, total: 231 ms
Wall time: 232 ms


In [22]:
#torch gpu
%%time
for i in range(1000):
  var1=torch.randn(100,100,device=cuda0)
  var2=torch.randn(100,100,device=cuda0)
  var3=var1+var2

CPU times: user 41.6 ms, sys: 663 µs, total: 42.2 ms
Wall time: 47.9 ms


In [0]:
tens=torch.ones((5,7,10,2))

In [27]:
print(tens.shape)

torch.Size([5, 7, 10, 2])


#auto grad function in torch


In [0]:
x=torch.tensor([7],dtype=torch.float64,requires_grad=True,device=cuda0)
y=torch.tensor([5],dtype=torch.float64,requires_grad=True,device=cuda0)

In [0]:
z = ((x**4)*(y**2)) + ((x**2)*y)

In [0]:
total=torch.sum(z)

In [32]:
total

tensor(60270., device='cuda:0', dtype=torch.float64, grad_fn=<SumBackward0>)

In [0]:
total.backward()

In [34]:
print(x.grad,y.grad)

tensor([34370.], device='cuda:0', dtype=torch.float64) tensor([24059.], device='cuda:0', dtype=torch.float64)
